create table role (id int8 generated by default as identity, role_name varchar(255), primary key (id));
create table user_role (id_user int8 not null, id_role int8 not null, primary key (id_user, id_role));
create table users (id int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists user_role add constraint FK2aam9nt2tv8vcfymi3jo9c314 foreign key (id_role) references role;
alter table if exists user_role add constraint FKr53t650tbjk5yipcm228wf1nc foreign key (id_user) references users;
