create table boardgame (id int8 generated by default as identity, name varchar(255), rent_value float8, primary key (id));
create table boardgame (id int8 generated by default as identity, name varchar(255), rent_value float8, primary key (id));
